# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#job-templates-with-parameters
jobs:
  - job: ${{ parameters.name }}
    pool: ${{ parameters.pool }}
    timeoutInMinutes: 15 # how long to run the job before automatically cancelling
    steps:
      - task: NodeTool@0
        displayName: "Use Node 12.x"
        inputs:
          versionSpec: 12.x

      - bash: |
          set -ex

          yarn install
          yarn build
        displayName: Build

      - publish: $(System.DefaultWorkingDirectory)/dist
        artifact: dist
      
      - script: |
        package_version=$(cat ./$(System.DefaultWorkingDirectory)/BedrockPackage/package.json | grep "version" | sed -e 's/"version": "//g')
        echo $package_version | sed -e 's/ //g' > version.txt
      
      - publish: $(System.DefaultWorkingDirectory)/version.txt
        artifact: BedrockVersion
