  
#parameters:
#  GitHubConnection: "" # defaults for any parameters that aren't specified

resources:
  repositories:
  - repository: BedrockHomebrewCore # The name used to reference this repository in the checkout step
    type: github
    endpoint: edaena
    name: edaena/homebrew-core

jobs:
  - job: Create_Github_Release
    timeoutInMinutes: 30 # timeout on job if deploy is not completed in 30 minutes
    pool:
      vmImage: ubuntu-16.04
    steps:
      - checkout: self
      - checkout: BedrockHomebrewCore
        persistCredentials: true
        clean: true
      - script: |
          dir $(Build.SourcesDirectory)
          echo "ls:"
          ls
          echo "pwd:"
          pwd
          cd homebrew-core
          git pull origin master
          git checkout -b master
          # Set git identity
          git config user.email "admin@azuredevops.com"
          git config user.name "Automated Account"
          touch readme2.md
          git branch update
          git checkout update
          sha_number="testsha9d"
          release_url="https:\/\/hi.com"
          sed "s/url \".*\"/url \"$release_url\"/g" ./Formula/bedrock-cli-test.rb >> bedrock-cli-test.rb
          sed "s/sha256 \".*\"/sha256 \"$sha_number\"/g" ./Formula/bedrock-cli-test.rb >> ./Formula/bedrock-cli-test.rb
          git add -f ./Formula/bedrock-cli.rb
          git commit -m "Update formula"
          git push origin update
          #git push origin master
      