  
#parameters:
#  GitHubConnection: "" # defaults for any parameters that aren't specified
parameters:
  GitHubConnection: "" # defaults for any parameters that aren't specified
  tagSource: "gitTag"

jobs:
  - job: Update_Homebrew_Formula
    timeoutInMinutes: 30 # timeout on job if deploy is not completed in 30 minutes
    pool:
      vmImage: ubuntu-16.04
    steps:
      - download: current
      - task: DownloadPipelineArtifact@2
        inputs:
          artifact: 'BedrockPackage'
          path: $(Agent.BuildDirectory)
      - checkout: BedrockHomebrewCore
        persistCredentials: true
        clean: true
      - script: |
          # Read version and sha256 number
          sha_number=$(sed -n '2p' < $(Agent.BuildDirectory)/BedrockPackage/package-info.txt)
          version_tag=$(sed -n '1p' < $(Agent.BuildDirectory)/BedrockPackage/package-info.txt)
          echo "version tag"
          echo $version_tag

          dir $(Build.SourcesDirectory)
          cd $(Build.SourcesDirectory)

          # Add changes to the homebrew formula repository
          git pull origin master
          git checkout -b master

          # Set git identity
          git config user.email "admin@azuredevops.com"
          git config user.name "Automated Account"
          
          release_url="https:\/\/github.com/microsoft/homebrew-bedrock/releases/download/$version_tag/dist.tar.gz"
          echo "release_url"
          echo $release_url

          cd Formula
          #sed -i ".txt" "s/url \".*\"/url \"$my_new_url\"/g" bedrock-cli-test.rb
          #sed -i "s/url \".*\"/url \"$release_url\"/g" bedrock-cli.rb
          sed -i ".txt" "s/\"https.*\.tar\.gz\"/\"$release_url\"/g" bedrock-cli.rb
          cat bedrock-cli.rb
          sed -i "s/sha256 \".*\"/sha256 \"$sha_number\"/g" bedrock-cli.rb
          cat bedrock-cli.rb

          git add -f bedrock-cli.rb
          git commit -m "Update formula with new release."
          
          git push origin master
      